### ISSUE TITLE
Required @babel/runtime as a dependency

### ISSUE THREAD

**Issue by aih** [cheton/github-release-cli#25]
I installed v2.0.0 of `github-release-cli` and when I first ran it, I got the following error:
`Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'`. Following a Google trail, I found that `@babel/runtime` needed to be installed as a dependency, so I manually installed it (`npm install -g @babel/runtime`), and the cli worked.

This suggests that `@babel/runtime` should be a required dependency in the `package.json`. I see that `package.json` has `"babel-runtime": "^6.26.0",`, but this apparently didn't work for me.

I was installing on RHEL 7.0

**Comment by hex0cter** [comment]
@cheton can you have a look at https://github.com/cheton/github-release-cli/pull/26 when you have time?

**Comment by cheton** [comment]
fixed in [v2.1.0](https://github.com/cheton/github-release-cli/releases/tag/v2.1.0)
