### ISSUE TITLE
Github Enterprise Usage? 

### ISSUE THREAD

**Issue by NateZimmer** [cheton/github-release-cli#6]
So github enterprise would have a unique URL such as 

https://my_company.com/api/v3/[normal_request_header]

Should be an easy feature if not already there to add support to pass a custom URL as an argument to support Github Enterprise

**Comment by cheton** [comment]
The `baseUrl` option allows you specifying a custom URL for GitHub Enterprise support:
https://github.com/octokit/rest.js#client-options

Do you mind creating a pull request to add a `--baseurl` option?

It might look something like this:
```js
program
    .option('--baseurl <baseurl>', 'API endpoint', 'https://api.github.com')
```

```js
const octokit = new Octokit({
    baseUrl: program.baseurl,
    // other options
});
```
